insert into ${settings.database.duff.schema}.beer_playlist(beer_id,playlist_id) values (1,'3G1xCbQ7sajECWrXLIA3TG');
insert into ${settings.database.duff.schema}.beer_playlist(beer_id,playlist_id) values (2,'3G1xCbQ7sajECWrXLIA3TG');
insert into ${settings.database.duff.schema}.beer_playlist(beer_id,playlist_id) values (3,'3G1xCbQ7sajECWrXLIA3TG');
insert into ${settings.database.duff.schema}.beer_playlist(beer_id,playlist_id) values (4,'3G1xCbQ7sajECWrXLIA3TG');
insert into ${settings.database.duff.schema}.beer_playlist(beer_id,playlist_id) values (5,'3G1xCbQ7sajECWrXLIA3TG');
insert into ${settings.database.duff.schema}.beer_playlist(beer_id,playlist_id) values (6,'3G1xCbQ7sajECWrXLIA3TG');
insert into ${settings.database.duff.schema}.beer_playlist(beer_id,playlist_id) values (7,'3G1xCbQ7sajECWrXLIA3TG');
insert into ${settings.database.duff.schema}.beer_playlist(beer_id,playlist_id) values (8,'3G1xCbQ7sajECWrXLIA3TG');
insert into ${settings.database.duff.schema}.beer_playlist(beer_id,playlist_id) values (9,'3G1xCbQ7sajECWrXLIA3TG');